sudo: required
language: node_js
node_js:
  - 10
services:
  - docker
before_install:
- docker pull motivationzone/dbservice
- docker run -d -p 127.0.0.1:80:80

# TODO make script to create db.yaml from env
# TODO create deploy on remote server from different branches
# from testing and production brunches
