enum HttpErrors {
    MISSING_PARAMS = 'MISSING_PARAMS',
    MISSING_REQUIRED_FIELD = 'MISSING_REQUIRED_FIELD',
    MISSING_LIMIT_PARAMS = 'MISSING_LIMIT_PARAMS',
    INVALID_PHONE_NUMBER = 'INVALID_PHONE_NUMBER',
    INVALID_EMAIL = 'INVALID_EMAIL',
    WRONG_DATA = 'WRONG_DATA'
}

export default HttpErrors;
